# Adds the "Sponsor" button to the repository.
github: [stin90]
ko_fi: stin90
# buy_me_a_coffee: <handle>                # add once set up
# custom: ['https://paypal.me/<handle>']   # add once set up
